webtalk_init -webtalk_dir C:/Users/junhe/Desktop/School/Y3/EE2026/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/sim20kHz_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 30 16:56:40 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3729f755-a973-468e-93de-80ed65c343c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0917254c695c4cb5998f17b74e73445e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "63609760 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1427533131 -regid "" -xml C:/Users/junhe/Desktop/School/Y3/EE2026/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/sim20kHz_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/junhe/Desktop/School/Y3/EE2026/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/sim20kHz_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/junhe/Desktop/School/Y3/EE2026/SoundDisplay/SoundDisplay/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/sim20kHz_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
